[DEVSU-1694] bugfix AlertDialog
bcgsc/pori_ipr_client pull request #131
Opened 2021-12-07 01:15 UTC by kttkjl

- Added additional handling in AlertDialog component
- Updated type of AlertDialogProps

DEVSU-1694

2021-12-07 19:43 UTC, elewis2 approved these changes

2021-12-07 20:13 UTC, areisle requested changes

2021-12-07 21:35 UTC, kttkjl commented on app/components/AlertDialog/index.tsx
> +    <Dialog open={isOpen} onClose={handleClose}>
Ah, I have been confused by the part by the callback passed in from parent components, good catch

2021-12-07 23:49 UTC, elewis2 submitted a review, later dismissed

2021-12-08 00:12 UTC, areisle reviewed
like the added tests :) just a couple comments about readability and the snap file

2021-12-08 00:12 UTC, areisle commented on app/components/AlertDialog/__tests__/AlertDialog.test.tsx
> +  test('It calls onClose with the correct params', () => {
I would split this into 2 tests, one for returns true for confirmed when confirm is clicked and one for returns false for confirmed when cancel is clicked

2021-12-08 00:12 UTC, areisle commented on app/components/AlertDialog/__tests__/AlertDialog.test.tsx
> +  let component = render(
this would be better inside the test. it makes it clearer what test this is for, and it's only used by the one test anyway

2021-12-08 00:12 UTC, areisle commented on app/components/AlertDialog/__tests__/__snapshots__/AlertDialog.test.tsx.snap
> +exports[`AlertDialog It renders 1`] = `<DocumentFragment />`;
I think I wouldn't bother with a snapshot in this case since this isn't including a snapshot of the dialog content anyway

2021-12-09 00:13 UTC, areisle approved these changes

2021-12-10 02:30 UTC, merged