[DEVSU-1871] adminview/user error handling
bcgsc/pori_ipr_client pull request #271
Opened 2022-10-21 01:06 UTC by kttkjl

- add snackbar messages to denote which step messed up

DEVSU-1871

2022-10-28 19:19 UTC, elewis2 commented
I'm actually getting two popups when a user is successfully created or edited - a black one above a green one

2022-10-28 19:21 UTC, elewis2 requested changes
There are two popups when a user record is created or edited - one black over one green. Probably only the green one is needed

2022-10-31 23:18 UTC, kttkjl commented
> There are two popups when a user record is created or edited - one black over one green. Probably only the green one is needed

Oh whoops, that wasn't taken into account -- will fix

2022-11-17 01:14 UTC, Nithriel approved these changes

2022-11-17 18:42 UTC, elewis2 approved these changes

2022-11-17 18:50 UTC, merged