Feature/devsu 1158 delete kb match rows
bcgsc/pori_ipr_client pull request #35
Opened 2021-03-04 23:53 UTC by Anna-log7

- Standardized kb-matches page/changed to TS
- Can now delete a row in the tables
- Fixed a bug where the wrong appendix would show up in the print report

2021-03-11 23:37 UTC, Anna-log7 commented on app/views/ReportView/components/KbMatches/index.tsx
> +  }, [groupedMatches, report, snackbar]);
I can't seem to replicate this. Can you link me a report where this happens?

2021-03-17 15:42 UTC, Anna-log7 commented on app/views/ReportView/components/KbMatches/index.tsx
> +  }, [groupedMatches, report, snackbar]);
Fixed after some testing

2021-03-17 17:23 UTC, kttkjl requested changes

2021-03-17 19:21 UTC, kttkjl approved these changes

2021-03-17 21:21 UTC, merged