Chore/npm package updates
bcgsc/pori_ipr_client pull request #350
Opened 2023-09-13 03:04 UTC by kttkjl

[No ticket] NPM package updates -- it's about time

- Updated most packages 
- Fixed tests and settings files related to package updates
- React is staying at v17 for now, seems like it breaks more tests
- Let's not talk about how the js-keycloak adapter skipped 12 versions

2023-09-13 16:31 UTC, elewis2 requested changes

2023-09-13 16:31 UTC, elewis2 commented on .github/workflows/npm-test.yml
> +        node: [16]
add node 18, add node 20 if possible

2023-09-18 19:47 UTC, kttkjl commented on .github/workflows/npm-test.yml
> +        node: [16]
done, seem to work fine in the builds

2023-09-26 17:46 UTC, elewis2 approved these changes

2023-09-28 01:10 UTC, merged