Feature/devsu 1416 pathway legend updates
bcgsc/pori_ipr_client pull request #40
Opened 2021-03-22 22:02 UTC by Anna-log7

This PR is for changing the pathway legend page to react, and adding support for custom pathway images if the option is specified in the report upload.
Available at `/pathway-analysis`

2021-03-25 21:54 UTC, Anna-log7 commented on .eslintrc.json
> +    "no-unused-vars": "off",
Yes. I looked it up and the `@typescript-eslint` plugin covers these and it's recommended to disable the base rules

2021-03-26 00:21 UTC, kttkjl commented
Noticed the checkmark on click for "UPLOAD PATHWAY LEGEND", it does the async timeout for "loading" but this is just opening up a window for users to choose a file for upload

2021-03-26 00:31 UTC, kttkjl requested changes
Noticed the checkmark on click for "UPLOAD PATHWAY LEGEND", it does the async timeout for "loading" but this is just opening up a window for users to choose a file for upload, and nothing about the image upload in-progress 

edit: you can circumvent the problem of no spinning loading circles by having a cleanup in AsyncButton's useEffect block

```javascriptReact  
useEffect(() => {
    let timeoutReturn;
    if (!isLoading && loadingStarted) {
      timeoutReturn = window.setTimeout(() => setLoadingStarted(false), 3000);
    }
    return () => clearTimeout(timeoutReturn);
  }, [isLoading, loadingStarted]);
```

otherwise PR looks good

2021-03-30 21:39 UTC, Anna-log7 commented
> 
> 
> Noticed the checkmark on click for "UPLOAD PATHWAY LEGEND", it does the async timeout for "loading" but this is just opening up a window for users to choose a file for upload, and nothing about the image upload in-progress
> 
> edit: you can circumvent the problem of no spinning loading circles by having a cleanup in AsyncButton's useEffect block
> 
> ```
> useEffect(() => {
>     let timeoutReturn;
>     if (!isLoading && loadingStarted) {
>       timeoutReturn = window.setTimeout(() => setLoadingStarted(false), 3000);
>     }
>     return () => clearTimeout(timeoutReturn);
>   }, [isLoading, loadingStarted]);
> ```
> 
> otherwise PR looks good

On second look, I don't think the `AsyncButton` should be used here. The button depends on the `onClick` event, but that will fire before the file is selected. I'll use a regular `Button` instead in this case

2021-03-31 19:12 UTC, kttkjl submitted a review, later dismissed

2021-04-20 19:28 UTC, kttkjl submitted a review, later dismissed

2021-04-20 19:37 UTC, kttkjl commented
Replacing the async button fixes the clicking problem and the problem you described, but the user won't have an indicator whether or not their custom legend is being uploaded, the async progress should be shown somewhere else

2021-04-23 18:57 UTC, kttkjl approved these changes

2021-04-23 19:09 UTC, merged