Feature/devsu 1487 use react in presentation sections
bcgsc/pori_ipr_client pull request #45
Opened 2021-04-09 19:26 UTC by Anna-log7

I refactored the slides and discussion sections to use React as well as adding tests for their components.

2021-04-21 00:00 UTC, kttkjl requested changes
Running into problems when the user does not have enough permission to edit the page on slides, choose a name and press upload

1. The dialog comes up asking "Editing this report will ...etc ", but be completely unable to press cancel, due to React components being unmounted already

2. User gets a refreshed page and nothing happens

Shouldn't edit options be disabled if the user has no rights to it?

2021-04-23 18:46 UTC, Anna-log7 commented on app/views/ReportView/components/Slides/components/UploadSlide/index.tsx
> +    <>
The `isSigned` check actually isn't needed here as the API request doesn't remove the signatures. I've removed it now.

Also fixed the select file styling

2021-04-23 19:49 UTC, kttkjl commented on app/views/ReportView/components/Slides/components/UploadSlide/index.tsx
>          className="text-field-fix"
seems like the `.text-field-fix` causes margin problems 
![image](https://user-images.githubusercontent.com/25511396/115922852-46ea1c80-a432-11eb-91c8-56d4971647a3.png)

2021-04-27 19:15 UTC, kttkjl approved these changes

2021-04-27 19:16 UTC, merged

2021-04-27 19:16 UTC, kttkjl commented on app/views/ReportView/components/Slides/components/UploadSlide/index.tsx
> +    <>
Permission problems not reproducible at this point ... might be GSC backend problems with keycloak, approving now