Feature/devsu 1469 ref alt in tgr
bcgsc/pori_ipr_client pull request #46
Opened 2021-04-13 19:32 UTC by Anna-log7

This PR adds in ref/alt data from the small mutation endpoint to the genomic events table in the probe summary.
I refactored the PrintTable component to generalize its use as well. This is due to ag-grid not handling long amounts of text/sizing issues in the print view with ag-grid tables.

2021-04-22 06:48 UTC, kttkjl reviewed
Weird, did the API change? `/me` shows me a 400 telling me `message: "Invalid authorization token"`

2021-04-22 16:43 UTC, Anna-log7 commented on app/components/PrintTable/index.tsx
> +              <tr key={index} className="table__row">
There's no common key, no

2021-04-22 16:45 UTC, Anna-log7 commented on app/views/ReportView/components/ProbeSummary/columnDefs.ts
> +    colId: 'Sample',
Yes, but I access the colId from columnDefs in the printTable for sorting so it needs to be defined initially

2021-04-22 16:46 UTC, Anna-log7 commented on app/views/ReportView/components/ProbeSummary/index.tsx
> +  loadedDispatch: ({ 'type': string }) => void;
Nope, that's right haha
It should pass `{ type: 'typehere' }`

2021-04-22 20:47 UTC, kttkjl commented on app/components/PrintTable/index.tsx
> +              <tr key={index} className="table__row">
Seeing a load of errors on react calling out the keys, but I suppose if they're not needing updates I suppose it's .... fine? 

Perhaps you can have a prop here that specifies the `name` of this specific `PrintTable`, then with index and then the actual row name

2021-04-22 20:48 UTC, kttkjl commented on app/components/PrintTable/index.tsx
> +              <tr key={index} className="table__row">
Actually yeah, if you're generalizing a PrintTable perhaps it's best to give a prop telling WHICH PrintTable it is

2021-04-22 23:58 UTC, kttkjl requested changes
Add prop to PrintTable to allow for uniquely identifying each PrintTable

2021-04-23 17:02 UTC, Anna-log7 commented on app/components/PrintTable/index.tsx
> +              <tr key={index} className="table__row">
The key errors are in a different component in the appendices unfortunately. The line you commented about is per row of the table, so I don't think a `name` for the table itself would solve the issue here

2021-04-23 17:35 UTC, kttkjl commented on app/components/PrintTable/index.tsx
> +              <tr key={index} className="table__row">
flagged wrong line, key should be ok here

ran into problems with `in table (created by ConfigTable)` having the <tr> having "" as key

2021-04-23 19:52 UTC, kttkjl approved these changes

2021-04-27 18:07 UTC, merged