Feat/DEVSU-2247 Add Search Reports by Variant Feature
bcgsc/pori_ipr_client pull request #510
Opened 2024-07-03 22:34 UTC by bnguyen-bcgsc

- Add search view to search for reports with specific variant
- Create new reports view for search result
- Validate input variant value
- Add new icon and search menu item to sidebar
- Add support for svg import to typescript config
- Code linting

2024-07-26 15:57 UTC, elewis2 commented on app/views/SearchView/index.tsx
> +const MIN_WORD_LENGTH = 3;
there are genes with 2-letter names - reduce this to 2

2024-07-26 17:59 UTC, elewis2 approved these changes

2024-07-29 17:12 UTC, elewis2 submitted a review, later dismissed

2024-07-29 19:39 UTC, kttkjl requested changes
Some comments on styling on ticket as well

2024-07-29 20:28 UTC, bnguyen-bcgsc commented on app/utils/searchReportsColumns.js
> +function searchReportsColumns(report, analyst, reviewer, bioinformatician) {
Yea I think we might reuse it with future advanced search features (when searching for reports using other fields than key variant)

2024-07-29 22:16 UTC, kttkjl commented on app/views/SearchView/index.tsx
>          <div className="search__threshold-input" onKeyUp={(event) => event.keyCode === ENTER_KEYCODE && handleSubmit()}>
keycode is deprecated, we should use key instead

2024-07-29 23:30 UTC, kttkjl approved these changes

2024-07-29 23:43 UTC, merged