Add pharmacogenomic section to genomic report
bcgsc/pori_ipr_client pull request #62
Opened 2021-06-01 23:13 UTC by Anna-log7

-- not to be included in the coming release --
This is to add a new section called pharmacogenomic to the genomic report under the germline header. `/pharmacogenomic`

2021-06-02 16:47 UTC, elewis2 submitted a review, later dismissed

2021-06-02 23:20 UTC, kttkjl requested changes
types would be nice, but code looks fine 

I've been told there was no report that had pharmacogenomic data on it; tried to search id based on ticket, no cake

2021-06-02 23:20 UTC, kttkjl commented on app/views/ReportView/index.jsx
> +                />
non blocker, it doesn't look like `routeProps` is being used in Pharmacogenomic here (it's just to conform to how it's set up)?
but a new way of using Route without the `render` shenanigans is 

```
<Route path={`${path}/pharmacogenomic`}>
  <Pharmacogenomic print={false} />
</Route>
```

and then use hooks inside the component to get the route params you want so it's more clear in the actual component what you need from the router

2021-06-15 17:43 UTC, kttkjl approved these changes

2021-06-15 23:30 UTC, elewis2 approved these changes

2021-06-15 23:35 UTC, merged